from random import randrange
from math import ceil
from color import Color

toxicity = 0
maxtime = 200
tM = 0
physPowe = randrange(100, 500)
physPower = ceil(physPowe)
armor = physPower // 50
time = 0
inventory = []
gold = 0
hpModifier = 0
hpMreq = 20
healthMod = 0
fullhp = 100
hp = fullhp
handmodifier = 0
barehand = physPower // 25
hand = barehand + handmodifier
kick = int((barehand * 2) // 1.5)
fistMastery = 0
kickMastery = 0
fMreq = 10
kMreq = 20
fistModifier = 5
kickModifier = 10
fistLvL = 1
kickLvL = 1
maxki = 50
ki = maxki
kiRecovery = randrange(1, 6)
kiPower = randrange(200, 700)
kPM = 10
pPM = 10
mkM = 100
kiMastery = 0
kiMreq = 5000
kiModifier = 1
kiLvL = 1
kiControl = 1
culLvL = 1
culReq = 500
pill = 0
h = 0
t = 0
genkai = 0
regeneration = 1
skills = ['Pressure Point ', 'atk', 10, 5, Color.White, 300, 'Neutral']
timer = 0
stash = ['Shmon +1 тт', 1]
char = 0
refKi = 50
physBody = ['CLOSED', 'CLOSED', 'CLOSED', 'CLOSED', 'CLOSED', 'CLOSED', 'CLOSED', 'CLOSED']
year = 18
month = 0
week = 0
day = 0
hour = 0
minute = 0
chronology = year, month, week, day, hour, minute
talent = randrange(1, 11)
maxYear = randrange(70, 90)
bonus = ['*`Chudo Rastenie +5 тт', 1]
if talent < 5:
    inventory.extend(bonus)
curSkills = ['Pressure Point', 'Fire Pressure']
curTechs = ['Lightning', 'Drain']
elements = ['Neutral', 'Fire', 'Wind', 'Earth', 'Water']
mainElem = 'Neutral'
neutElem = 10
fireElem = 10
windElem = 10
earthElem = 10
waterElem = 10
indElem = 0
elems = [neutElem, fireElem, windElem, earthElem, waterElem]
mainElemPow = 0